### ISSUE TITLE
Nueva implementación - Codigo Promocional

### ISSUE THREAD

**Issue by manelcecs** [manelcecs/scrume#157]
### Descripción
Permitir al usuario introducir un código promocional para canjearlo por un mes pro gratis.
- Permitir en un nuevo registro.
- Si estás registrado ya puedes introducirlo.
- Códigos de un solo uso.
- Si ya tenia días pagados, hacer una conversion al equivalente al nuevo plan.

### Checklist
- [x] Añadir un campo para añadir el código promocinal en el registro.
- [x] Permitir actualizar el plan de un usuario registrado con o sin código
- [x] Permitir al administrador ver los códigos aún activos y generar nuevos.

### Aceptación 
POR DEFINIR Q/A

**Comment by davcamalv** [comment]
¿Qué pasa en caso de pasar del plan pro x ejemplo al basic? Entiendo que el usuario pierde los dias que ha pagado. Otra alternativa es no permitir ese cambio y solo permitir cambios de basic a pro/standard o entre los planes pro y standard.

**Comment by manelcecs** [comment]
> 
> 
> ¿Qué pasa en caso de pasar del plan pro x ejemplo al basic? Entiendo que el usuario pierde los dias que ha pagado. Otra alternativa es no permitir ese cambio y solo permitir cambios de basic a pro/standard o entre los planes pro y standard.

Pues ya te respondí, para que quede constancia. Cuando se pase de un standard a pro, los dias restantes se dividirán entre 2.
Si es de pro a standard, se multiplican por 2.
