### ISSUE TITLE
Ver podcast de Trinidad

### ISSUE THREAD

**Issue by EzequielPJ** [manelcecs/scrume#175]
Se debe de ver el podcast de Trinidad antes de las 19:00 del día 15/05/2020 e ir apuntando todos lo que se vea interesante para después comentárselo al grupo en una reunión a posteriori.

**Comment by aleks-rodriguez** [comment]
- Tener "una historia que contar", con métricas que reflejen el trabajo realizado.
- No hablar con los inversores antes del "demo day", porque asi ellos saben que le puede salir mas barato, ademas de que el poder trabajar hasta el dia de esa demo puede cambiar las metricas de la app y revalorizarlas
- Es necesario tener unos objetivos bien definidos, si no, la empresa no va a ir a ningun lado y se va a quedar estancada.
