### ISSUE TITLE
Rentabilidad de la aplicación tras conseguir el ROI

### ISSUE THREAD

**Issue by EzequielPJ** [manelcecs/scrume#185]
## Descripción
Se debe de analizar cuando dinero se conseguiría cada mes tras llegar a superar nuestro ROI (es decir cuando compensemos la inversión final) y ver si el dinero que supuestamente ganamos es suficiente y por tanto nuestros precios son correctos.
Se debe de documentos los beneficios y también las gastos que seguimos teniendo.

## Checklist
- [x] Se han documentado los beneficios y gastos que tendremos trás el ROI.

**Comment by Erick328** [comment]
Yo vine aquí buscando el código, no un blog.

**Comment by manelcecs** [comment]
Tienes un monólogo en Cartuja o cómo va la cosa? @Erick328

**Comment by antcarluq** [comment]
Yo vine aquí buscando mis ganas de vivir, no un blog.

**Comment by davcamalv** [comment]
Venir a una issue a buscar código es como ir a la montaña y buscar tiburones
