### ISSUE TITLE
Son necesarios mas datos en el JWT

### ISSUE THREAD

**Issue by jualorper** [manelcecs/scrume#69]
Para comprobar que el usuario logueado tiene permisos según su plan contratado, sería necesario que se mandase dicho plan (BASIC, STANDARD o PRO). 
Además, propongo que se modifique el date que se manda, que en lugar de ser un objeto, sea una string en formato ISO.
https://stackoverflow.com/questions/10286204/the-right-json-date-format
https://www.baeldung.com/jackson-serialize-dates
![image](https://user-images.githubusercontent.com/35260622/78427053-26f38980-7674-11ea-8ec8-4e996ea78a28.png)

**Comment by angel96** [comment]
El apartado del nombre del paquete esta resuelto. El formato de la fecha estoy aun ello. @jualorper

**Comment by angel96** [comment]
En la siguiente subida, al terminar el PDF se reflejará este cambio. La fecha llevará un formato yyyy-MM-dd y el token ira reforzado con comprobaciones sobre el DTO que manda.

**Comment by jualorper** [comment]
Algun motivo concreto para no usar el formato ISO?

**Comment by angel96** [comment]
Por sencillez de formato, lo requereis especificamente en dicho formato? Lo digo porque es una fecha, no una fecha y una hora determinada.

**Comment by manelcecs** [comment]
#70 Reabre esta issue

**Comment by angel96** [comment]
Cierro con el comentario en la issue #70
