### ISSUE TITLE
Problema con JWT

### ISSUE THREAD

**Issue by manelcecs** [manelcecs/scrume#70]
### Preludio
El jueves se implementó el JWT y se quedó correctamente funcionando.
Ayer sabado, se transmitió una incidencia de mejora respecto a la información que suministra dicho token (#69).

### Estado actual
Tras realizar esta implementación solicitada, el funcionamiento normal de dicho token no ha sido continuado, obteniendo como respuesta un HTTP Response 500.

### Solución momentanea
Se restablece la versión anterior a dicha implentación con el funcionamiento habitual del JWT para la autenticación.

### Se pide

1. Solucionar el problema para aportar la funcionalidad requerida en el issue referenciada.
2. Subir la versión con la nueva funcionalidad y el funcionamiento correcto de la autenticación.
3. Probar exhaustivamente cada nueva implementación, ya que lo nuevo no debe romper lo anterior.

**Comment by angel96** [comment]
**Se pide**

* Solucionar el problema para aportar la funcionalidad requerida en el issue referenciada.

La funcionalidad ha sido resuelta. El problema ha sido un mal entendido entre formatos ISO de fechas. Cosa que ya he hablado con mi homologo

* Subir la versión con la nueva funcionalidad y el funcionamiento correcto de la autenticación.

Reitero sobre lo anterior, se ha comprobado la solvencia de la incidencia sobre el propio servidor de producción para evitar asuntos de cache y funciona correctamente.

* Probar exhaustivamente cada nueva implementación, ya que lo nuevo no debe romper lo anterior.

De conformidad con lo requerido, no procede en este caso considerar este hecho. Dado que, desde un comienzo no se ha hecho explicito el formato de fecha pedido. Se ha tratado de resolver conforme a supuestos. A efectos reales, no debería ser así.
