### ISSUE TITLE
Peticiones para gestionar el equipo

### ISSUE THREAD

**Issue by jualorper** [manelcecs/scrume#71]
## Introducción
La idea en front para gestionar el equipo es en la vista de editar el equipo, hacer un apartado con la lista de usuarios en los que se puedan eliminar a miembros, nombrar admins y salirse del equipo.
A esta vista de editar solo podría acceder el admin del equipo. 

---

#### Modificaciones
`api/team/list`: Para cada equipo, incluir si es admin.

#### Nuevas
`api/team/list-members/{idTeam}`: Listar los miembros de un equipo, en el que se incluyan: id, nickname, email y si es admin.
`team/{idTeam}`: Get de un equipo en el que se incluya el nombre, el id y si es admin.

#### Preguntas
`api/team/team-out/{idTeam}`: No se cual es la función de esta peticion.

---

Muchas gracias, estoy disponible para resolver cualquier duda.

**Comment by davcamalv** [comment]
la funcion de team-out es salirse del equipo en cuestion
