### ISSUE TITLE
Restricción al renovar el plan contratado

### ISSUE THREAD

**Issue by jualorper** [manelcecs/scrume#88]
## Descripción
Actualmente, se permite renovar el plan sin haber caducado antes. Con objetivo de simplificar las cosas y tras haberlo hablado con el coordinador de back, nos ha parecido que la mejor solución es que solo se pueda renovar el plan una vez ha caducado. 

## Solicitud
Poner la restricción en back de que no se puede renovar un plan si no ha caducado. Evidentemente, en front pondremos la validación pertinente también.

Muchas gracias, estoy disponible para resolver cualquier duda.

**Comment by angel96** [comment]
## Procedimiento y Análisis de resolución
Se ha obtenido el pago vigente del usuario, comprobando si la fecha actual es posterior a su fecha de expiración.
