### ISSUE TITLE
JWT token al realizar la renovación con éxito

### ISSUE THREAD

**Issue by jualorper** [manelcecs/scrume#89]
## Descripción
Al renovar el pago (`/api/payment/pay`), se devuelve un objeto que no es útil. Cuando se realiza este pago, el token queda desfasado y el usuario debe volver a loguearse para conseguir el token nuevo.

## Petición
Para mejorar la experiencia de usuario, pido que se devuelva unicamente el token al realizar con éxito la petición a `/api/payment/pay`.

Muchas gracias, estoy disponible para resolver cualquier duda al respecto.

**Comment by angel96** [comment]
## Procedimiento y Análisis de resolución

* Se ha generado un método específico que genere el token para la URL solicitada.
* Dicho método a partir del objeto cuenta de usuario permite generar el token.
* Se han detectado dos métodos que gestionan el pago. Uno para la inscripción y otro para la acción de pago por renove del plan. Este último ha sido el modificado.
