### ISSUE TITLE
No se genera la ventana de Paypal para efectuar Pago

### ISSUE THREAD

**Issue by angel96** [manelcecs/scrume#94]
## Circunstancia
* Este error se ha generado al estar actualizando el manual de usuario en la parte de registro.

## Campos introducidos en registro

* Correo: angeldelgadoluna@gmail.com
* Contraseña: 123456789Aa
* Plan: Pro

## Detalle de logs por parte de los navegadores Microsoft Edge y Google Chrome
![image](https://user-images.githubusercontent.com/16750517/79360151-cc93dc00-7f43-11ea-8016-6f83186209bf.png)

**Comment by angel96** [comment]
1. Comprobado con Postman en local y remoto al servidor en que se hospeda la API y puedo acceder a las dos URLs públicas sin problemas.

2. He probado con Token en blanco. Y funciona desde local y postman a la api en heroku. No establece la conexión adecuadamente desde la propia aplicación del front.

3. Analizando el código de front (URL: https://github.com/manelcecs/scrume-front/blob/master/src/app/servicio/user.service.ts), asumo que el error viene de lo siguiente, pongo adjunto textualmente el código en cuestión:

```
    getAllBoxes() : Observable<Box[]>{
      return this.httpClient.get<Box[]>(this.cabeceraService.getCabecera() + 
"api/box/all", {headers: this.cabeceraService.getBasicAuthentication()});
    }

    isValidEmail(email : string) : Observable<boolean> {
      let data = {"username": email};
      return this.httpClient.post<boolean>(this.cabeceraService.getCabecera() 
+ "api/login/isAValidEmail", data, {headers: this.cabeceraService.getBasicAuthentication()});
    }
```

Tal y como se muestra las dos peticiones con carácter público, estan tomando cabeceras de autenticación. Creo que esto no debería ser así porque trata de usar un token vacío de contenido siendo su UserAccount nula y los datos respectivos que generan el token nulos.

**Comment by jualorper** [comment]
Solucionado. 
Cierra la issue si ves que todo es correcto. Gracias!

**Comment by angel96** [comment]
La incidencia ha resuelta con exito. Cierro la issue.
