### ISSUE TITLE
Mejoras o Errores detectados

### ISSUE THREAD

**Issue by angel96** [manelcecs/scrume#95]
### Error 1 - Circunstancia
No salta ningun aviso de que mi loggeo es incorrecto

![image](https://user-images.githubusercontent.com/16750517/79360929-e4b82b00-7f44-11ea-83ae-32022b26aef6.png)

### Mejora 1 - Vista de tablero
Se propone la creación de banner flotante que al poner el ratón sobre las imagenes, cante el nombre de la persona adjudicada. Si hay mas de un usuario con emoticono normal no se diferencia.

### Mejora 2 - Vista de Crear Sprint
* Formato de fechas
* Desplegable

![image](https://user-images.githubusercontent.com/16750517/79362847-5f824580-7f47-11ea-85da-276d51cec3ba.png)

**Comment by jualorper** [comment]
Cerrada porque se ha solucionado.
Gracias!
